#!/bin/sh
# Stub to call main Komodo binary.

# Resolve all symlinks to this stub path.
STUB=$0
while [ -h "$STUB" ]; do
    ls=`ls -ld "$STUB"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    unset ls
    if expr "$link" : '/.*' > /dev/null; then
        STUB="$link"
    else
        STUB="`dirname $STUB`/$link"
    fi
    unset link
done

INSTALLDIR="`dirname $STUB`/.."
unset STUB
if test -f "$INSTALLDIR/../bin/is_dev_tree.txt"; then
    mozdir=$INSTALLDIR/../bin
else
    mozdir=$INSTALLDIR/lib/mozilla
fi
executable="$mozdir/komodo"

# Build a safe runtime library path before launching Komodo.
# We keep package-local locations first, then append filtered host paths.
safe_ld=""
add_ld_path() {
    _p="$1"
    [ -n "$_p" ] || return 0
    [ -d "$_p" ] || return 0
    case ":$safe_ld:" in
        *":$_p:"*) return 0 ;;
    esac
    if [ -n "$safe_ld" ]; then
        safe_ld="$safe_ld:$_p"
    else
        safe_ld="$_p"
    fi
}

add_ld_path "$mozdir"
add_ld_path "$mozdir/../lib"
add_ld_path "$mozdir/extensions/python/dist/bin"
add_ld_path "$mozdir/extensions/python/dist/lib"
add_ld_path "$INSTALLDIR/lib/mozilla"
add_ld_path "$INSTALLDIR/lib/python/lib"

# Keep known-good system runtime locations available.
add_ld_path "/usr/lib/x86_64-linux-gnu"
add_ld_path "/lib/x86_64-linux-gnu"

export LD_LIBRARY_PATH="$safe_ld"
unset safe_ld
unset _p
unset add_ld_path

# Drop host toolkit overrides that can pull Snap GTK/GIO modules into Komodo.
unset GTK_PATH
unset GTK_EXE_PREFIX
unset GTK_IM_MODULE_FILE
unset GTK_MODULES
unset GIO_MODULE_DIR
unset LOCPATH
unset GSETTINGS_SCHEMA_DIR

# Clear internal XRE/Komodo restart/profile vars from the parent env.
# If these leak into a fresh launcher call, koStart can skip argv parsing,
# which drops file-open arguments and breaks single-instance handoff.
unset _KOMODO_VERUSERDATADIR
unset XRE_PROFILE_PATH
unset _XRE_USERAPPDATADIR
unset XRE_PROFILE_LOCAL_PATH
unset XRE_PROFILE_NAME
unset XRE_START_OFFLINE
unset XRE_BINARY_PATH
unset MOZ_APP_RESTART
unset MOZ_LAUNCHED_CHILD
unset MOZ_CRASHREPORTER_RESTART_ARG_1
unset MOZ_CRASHREPORTER_EVENTS_DIRECTORY
unset INSTALLDIR

exe_type=`file "$executable"`
warn_arch ( ) {
    # This function just spits out a warning if we're trying to run a bad binary
    if [ -n "$KOMODO_FORCE_ARCH" ] ; then
        return # suppress arch warning
    fi
    case `uname -m` in
        x86_64)
            machine_arch=".*executable, x86-64, "
            wanted_arch="x86_64";;
        i?86)
            machine_arch=".*executable, Intel 80386, "
            wanted_arch="x86";;
        *)
            # I dunno what you're doing, hopefully you're smart enough
            return;;
    esac
    if [ "0" -ne `expr "$exe_type" : "$machine_arch"` ] ; then
        return # arch match
    fi
    "$mozdir/mozpython" -c ""
    if [ "$?" -eq "0" ] ; then
        return # can run given binary - maybe it's i686 on x86_64
    fi
    msg=`cat <<-EOF
	This Komodo binary is not meant for your computer's architecture.
	Please download the $wanted_arch version at:
	http://www.activestate.com/komodo-edit/downloads
	EOF
	`
    # Figure out a command to display errors with; assume $DISPLAY is set
    # (since you need that to run Komodo).  We try to use the GUI dialogs here
    # because stdout/stderr is probably redirected to a file.
    if which zenity ; then
        # Use the gtk error dialog
        zenity --error --text "$msg"
    elif which kdialog ; then
        # Use the KDE/Qt error dialog
        kdialog --error "$msg"
    else
        # Don't have anything, fall back to console
        printf "\033[31;1m$msg\033[0m\n" >&1
    fi
    unset msg
    # Run the executable anyway
}
warn_arch
unset warn_arch
unset machine_arch
unset wanted_arch
unset exe_type
unset mozdir
exec "$executable" "$@"
